export const LOGIN_ROUTE: string = '/login'
export const REGISTRATION_ROUTE: string = '/registration'
export const EDIT_ROUTE: string = '/edit'
export const WELCOME_ROUTE: string = '/' 
export const GROUP_ROUTE: string = '/group' 
export const PERSONAL_ROUTE: string = '/personal' 